CREATE SCHEMA IF NOT EXISTS filter;
CREATE SCHEMA IF NOT EXISTS condition;
CREATE SCHEMA IF NOT EXISTS screener;
CREATE SCHEMA IF NOT EXISTS expression;
CREATE SCHEMA IF NOT EXISTS watchlist;
CREATE SCHEMA IF NOT EXISTS mockfeed;