/**
 * Filter
 * These are filter service APIs
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PatchData { 
    /**
     * Action to be performed on given resource. 
     */
    operation: PatchData.OperationEnum;
    /**
     * The property of the json attribute to be replaced.
     */
    property: PatchData.PropertyEnum;
    /**
     * The new value of the json attribute to be patched.
     */
    value: string;
}
export namespace PatchData {
    export type OperationEnum = 'REPLACE';
    export const OperationEnum = {
        REPLACE: 'REPLACE' as OperationEnum
    };
    export type PropertyEnum = 'NAME' | 'DESCRIPTION' | 'CODE' | 'PARSE_TREE';
    export const PropertyEnum = {
        NAME: 'NAME' as PropertyEnum,
        DESCRIPTION: 'DESCRIPTION' as PropertyEnum,
        CODE: 'CODE' as PropertyEnum,
        PARSETREE: 'PARSE_TREE' as PropertyEnum
    };
}