openapi: 3.0.0
info:
  description: These are stock service APIs
  version: 1.0.0
  title: Stock
servers:
  - url: 'http://localhost:5005/'
  - url: 'https://localhost:5005/'
paths:
  /v1/stock:
    get:
      tags:
        - stock
      summary: get all stocks
      description: get stock list
      operationId: getAllStocks
      responses:
        '200':
          description: >-
            Request sucessfully processed.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StockResponse'
        '400':
          description: Request is not understood.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/stock/update:
    get:
      tags:
        - stock
      summary: update all stocks
      description: update stock list
      operationId: updateAllStocks
      parameters:
        - in: query
          name: exchange
          required: true
          schema:
            type: string
        - in: query
          name: url
          required: true
          schema:
            type: string
      responses:
        '200':
          description: >-
            Request sucessfully processed.
        '400':
          description: Request is not understood.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'                
components:
  schemas:
    StockResponse:
      required:
        - symbol
        - exchange
        - name
        - dol
      type: object
      properties:
        symbol:
          type: string
          description: symbol of stock
        exchange:
          type: string
          description: exchage that stock belongs to
        name:
          type: string
          description: name of stock
        series:
          type: string
          description: series of stock
        dol:
          type: string
          description: date of listing
          format: "date"
    Error:
      type: object
      properties:
        message:
          type: string
          description: brief information about error
        resolution:
          type: string
          description: possibly hints to solve the error
        errorCode:
          type: string
          description: pattern to unqiuely identify error root cause and origin.
          