name: Deploy Database Services

on:
  workflow_dispatch:
    inputs:
     StackNamePrefix:
      required: true
      description: Prefix for Stack Name
     ImageTag:
      required: true
      description: Image Tag
      default: 'latest'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy Database Services
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: ${{ github.event.inputs.StackNamePrefix }}-ECS-DB-Stack
          cdk_args: '--context stackPrefix=${{ github.event.inputs.StackNamePrefix }} --context imageTag=${{ github.event.inputs.ImageTag }}'
          working_dir: 'aws-infra'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
