name: Destroy ECR Repositories

on:
  workflow_dispatch:
    inputs:
     StackNamePrefix:
      required: true
      description: Prefix for Stack Name
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Destroy ECR Repositories
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'destroy'
          cdk_stack: ${{ github.event.inputs.StackNamePrefix }}-ECR-Stack
          cdk_args: '--context stackPrefix=${{ github.event.inputs.StackNamePrefix }} --require-approval never'
          working_dir: 'aws-infra'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
