name: Build and Push Database Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file database/com.bhs.gtk.db.app.master/pom.xml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.REPO_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.REPO_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: gtk-common-repo
        IMAGE_TAG: gtk.db.app.master
      run: |
        docker build database/com.bhs.gtk.db.app.master/ -f database/com.bhs.gtk.db.app.master/Dockerfile -t gtk-db-app-master --build-arg USER_NAME=${{ secrets.DB_USER_NAME }} --build-arg PASSWORD=${{ secrets.DB_PASSWORD }}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
