name: Test

on:
  workflow_dispatch:
    inputs:
     StackNamePrefix:
      required: true
      description: Prefix for Stack Name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV
        run: awscli
