name: Test

on:
  workflow_dispatch:
    inputs:
     StackNamePrefix:
      required: true
      description: Prefix for Stack Name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch cloudformation stack info
        id: cfnStackInfo
        run: echo ::set-output name=RAW_APP_URL::$(aws cloudformation --region ap-south-1 describe-stacks --stack-name ${{ github.event.inputs.StackNamePrefix }}-ECS-APP-Stack --query Stacks[0].Outputs[0].OutputValue)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
      - name: Fix raw app url
        id: fixUrl
        run: |
          RAW_URL=${{ steps.cfnStackInfo.outputs.RAW_APP_URL }}
          echo ::set-output name=APP_URL::$RAW_URL
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
      - name: Replace application load balancer url
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "appUrl"
          replace: "http://${{ steps.fixUrl.outputs.APP_URL }}"
          include: "**environment.prod.ts"      
      - name: Read environment.prod.ts
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./frontend/greentick-webapp/src/environments/environment.prod.ts
      - name: Echoenvironment.prod.ts
        run: echo "${{ steps.package.outputs.content }}"
