name: Test

on:
  workflow_dispatch:
    inputs:
     StackNamePrefix:
      required: true
      description: Prefix for Stack Name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get App Loadbalancer Url
        uses: hannut91/aws-cli@1.18.43
        with:
          args: aws help
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.REPO_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.REPO_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-south-1"
      - name: Get version
        id: vars
        run: echo ::set-output name=version::$(cat filter/README.md)
      - name: Test output
        run: echo ${{ steps.vars.outputs.version }}
