name: Test

on:
  workflow_dispatch:
    inputs:
     StackNamePrefix:
      required: true
      description: Prefix for Stack Name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV
        run: echo ::set-output name=MY_VAR::$(curl https://pypi.org/pypi/awscli/json | jq -r '.info.version')
