name: Test

on:
  workflow_dispatch:
    inputs:
     StackNamePrefix:
      required: true
      description: Prefix for Stack Name
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Application Load Balancer Url
        id: vars
        run: echo ::set-output name=appUrl::$(aws cloudformation --region ap-south-1 describe-stacks --stack-name ${{ github.event.inputs.StackNamePrefix }}-ECS-APP-Stack --query Stacks[0].Outputs[0].OutputValue)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
      - name: create prod environment config file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "environment.prod.ts"
          json: '{"production": true , "filterApiBasePath":"${{ steps.vars.outputs.appUrl }}"}'
          dir: 'frontend/greentick-webapp/src/environments/'
